server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://10.11.52.152:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456


mybatis:
  mapper-locations:
    - classpath: mapper/*.xml
    - classpath*: com/**/mapper/*.xml
